
import React,{Component} from 'react'
import {
    Row,
    Avatar,
    Col,
    Button,
    Input,
    Table,
    Dropdown,
    Menu,
    Select,
    Modal,
    Tabs,
    Icon,
} from 'antd'
import classnames from 'classnames'
import {Link} from 'react-router'
import NestedComponent from 'app/decorators/NestedComponent'
import DictUtils from 'app-utils/DictUtils'
import Layout,{Fixed,Pane} from 'app/components/Layout'
import ResumeDetailView from './ResumeDetail.view'
import styles from './styles.less'

const ButtonGroup = Button.Group;
const TabPane = Tabs.TabPane;



@NestedComponent()
export default class PersonInfoDetailSame extends Component{
  componentDidMount(){
    let {actions,params} = this.props
    actions.getSameResumeAction({id:params.resumeId})
  }
  jump2Another(id){

  }
  render(){
    let {reduce:{sameList},params:{resumeId}} = this.props
    sameList = [ {
  "orderKey" : "",
  "keyType" : "",
  "keyWord" : "",
  "id" : "52c2cc2233d84d3c9ad045aaba7f3247",
  "orgId" : "c9ef3376ba994d56baf5b49a942f7cb2",
  "resumeInfoId" : "F8BABB078BC21F868C827275AEE2E400",
  "resumeChannelId" : "514619565208",
  "channel" : 1,
  "photoUrl" : "https://mypics.zhaopin.cn/avatar/2018/3/28/5d21c887-0411-48d2-b40c-dc0ba4d1ab12.jpg",
  "name" : "孙小姐",
  "sex" : 2,
  "jobId" : "ce12a7e614644a318546decb56c96c1b",
  "jobTitleEmail" : "HRBP",
  "jobArea" : "",
  "readStatus" : 2,
  "downloadStatus" : 1,
  "status" : 0,
  "statusChangeTime" : "",
  "resumeType" : 1,
  "interviewLevel" : "",
  "interviewTime" : "",
  "isFeedback" : "",
  "isChangeDate" : "",
  "interviewer" : "",
  "offerSendTime" : "",
  "offerStatus" : "",
  "expectedEntryTime" : "",
  "remarkLabel" : "",
  "degree" : 5,
  "birthYear" : 1994,
  "startWorkingYear" : 2014,
  "maritalStatus" : 1,
  "mobilephone" : "17857402885",
  "email" : "239256528@qq.com",
  "currentAddress" : "浙江 宁波",
  "expectedAddress" : "[\"上海\"]",
  "expectedJobTitle" : "[\"人力资源\",\"行政/后勤/文秘\"]",
  "trade" : "[40]",
  "workStatus" : "",
  "company" : "吉利汽车",
  "lastJobTitle" : "综合管理专员",
  "lastJobStart" : "2014-07-01",
  "lastJobEnd" : "2099-01-01",
  "lastSchool" : "吉林大学",
  "lastMajor" : "工商管理",
  "lastSchoolStart" : "2012-08-01",
  "lastSchoolEnd" : "2016-07-01",
  "originalEmail" : "lilyaiduqing@aliyun.com",
  "originalWay" : 1,
  "isLock" : 1,
  "libType" : 1,
  "havaSame" : 0,
  "filingReason" : "",
  "filingRemark" : "",
  "filingTime" : "",
  "filingAcc" : "",
  "isNewFiling" : "",
  "adverseEvent" : "",
  "defined1" : "",
  "defined2" : "",
  "defined3" : "",
  "defined4" : "",
  "defined5" : "",
  "defined6" : "",
  "defined7" : "",
  "defined8" : "",
  "defined9" : "",
  "deliveryTime" : "2018-09-13 15:51:10",
  "remindFollowTime" : "",
  "inputTime" : "2018-09-13 15:51:10",
  "inputAcc" : "15546464646",
  "updateTime" : "2018-09-13 16:44:08",
  "updateAcc" : "15546464646",
  "isDel" : 0,
  "remarkLabels" : [ ],
  "degrees" : [ ],
  "workYears" : [ ],
  "jobIds" : [ ],
  "trades" : [ ],
  "notes" : [ ],
  "jobTitle" : "产品经理",
  "dept" : "",
  "age" : "",
  "workYear" : "",
  "resumeNums" : "",
  "ownerName" : "",
  "interviewers" : [ ],
  "hrAcc" : "",
  "ids" : [ ],
  "words" : "",
  "deleteType" : "",
  "resumeChannelIds" : [ ],
  "currentAcc" : "",
  "isFollowRemind" : "",
  "deliveryTimes" : [ ],
  "jobType" : "",
  "interviewStatus" : "",
  "searchInClient" : ""
}, {
  "orderKey" : "",
  "keyType" : "",
  "keyWord" : "",
  "id" : "c1a5c96420fb46f597db99f904e9129a",
  "orgId" : "",
  "resumeInfoId" : "",
  "resumeChannelId" : "514623009608",
  "channel" : 1,
  "photoUrl" : "",
  "name" : "李丹晖",
  "sex" : "",
  "jobId" : "81c795344d0e481fa551e6f881fc6687",
  "jobTitleEmail" : "",
  "jobArea" : "",
  "readStatus" : "",
  "downloadStatus" : "",
  "status" : 0,
  "statusChangeTime" : "",
  "resumeType" : 1,
  "interviewLevel" : "",
  "interviewTime" : "",
  "isFeedback" : "",
  "isChangeDate" : "",
  "interviewer" : "",
  "offerSendTime" : "",
  "offerStatus" : "",
  "expectedEntryTime" : "",
  "remarkLabel" : "",
  "degree" : "",
  "birthYear" : "",
  "startWorkingYear" : "",
  "maritalStatus" : "",
  "mobilephone" : "",
  "email" : "",
  "currentAddress" : "",
  "expectedAddress" : "",
  "expectedJobTitle" : "",
  "trade" : "",
  "workStatus" : "",
  "company" : "",
  "lastJobTitle" : "",
  "lastJobStart" : "",
  "lastJobEnd" : "",
  "lastSchool" : "",
  "lastMajor" : "",
  "lastSchoolStart" : "",
  "lastSchoolEnd" : "",
  "originalEmail" : "",
  "originalWay" : "",
  "isLock" : "",
  "libType" : 1,
  "havaSame" : "",
  "filingReason" : "",
  "filingRemark" : "",
  "filingTime" : "",
  "filingAcc" : "",
  "isNewFiling" : "",
  "adverseEvent" : "",
  "defined1" : "",
  "defined2" : "",
  "defined3" : "",
  "defined4" : "",
  "defined5" : "",
  "defined6" : "",
  "defined7" : "",
  "defined8" : "",
  "defined9" : "",
  "deliveryTime" : "",
  "remindFollowTime" : "",
  "inputTime" : "",
  "inputAcc" : "",
  "updateTime" : "",
  "updateAcc" : "",
  "isDel" : "",
  "remarkLabels" : [ ],
  "degrees" : [ ],
  "workYears" : [ ],
  "jobIds" : [ ],
  "trades" : [ ],
  "notes" : [ ],
  "jobTitle" : "招聘专员/助理（可接受实习生）",
  "dept" : "",
  "age" : "",
  "workYear" : "",
  "resumeNums" : "",
  "ownerName" : "",
  "interviewers" : [ ],
  "hrAcc" : "",
  "ids" : [ ],
  "words" : "",
  "deleteType" : "",
  "resumeChannelIds" : [ ],
  "currentAcc" : "",
  "isFollowRemind" : "",
  "deliveryTimes" : [ ],
  "jobType" : "",
  "interviewStatus" : "",
  "searchInClient" : ""
}, {
  "orderKey" : "",
  "keyType" : "",
  "keyWord" : "",
  "id" : "5593a26d7db14c3e98d44fc5bedd6070",
  "orgId" : "",
  "resumeInfoId" : "",
  "resumeChannelId" : "514634870308",
  "channel" : 1,
  "photoUrl" : "",
  "name" : "刘丽莉",
  "sex" : "",
  "jobId" : "4bc241771db148429e8aa42541be081b",
  "jobTitleEmail" : "",
  "jobArea" : "",
  "readStatus" : "",
  "downloadStatus" : "",
  "status" : 0,
  "statusChangeTime" : "",
  "resumeType" : 1,
  "interviewLevel" : "",
  "interviewTime" : "",
  "isFeedback" : "",
  "isChangeDate" : "",
  "interviewer" : "",
  "offerSendTime" : "",
  "offerStatus" : "",
  "expectedEntryTime" : "",
  "remarkLabel" : "",
  "degree" : "",
  "birthYear" : "",
  "startWorkingYear" : "",
  "maritalStatus" : "",
  "mobilephone" : "",
  "email" : "",
  "currentAddress" : "",
  "expectedAddress" : "",
  "expectedJobTitle" : "",
  "trade" : "",
  "workStatus" : "",
  "company" : "",
  "lastJobTitle" : "",
  "lastJobStart" : "",
  "lastJobEnd" : "",
  "lastSchool" : "",
  "lastMajor" : "",
  "lastSchoolStart" : "",
  "lastSchoolEnd" : "",
  "originalEmail" : "",
  "originalWay" : "",
  "isLock" : "",
  "libType" : 1,
  "havaSame" : "",
  "filingReason" : "",
  "filingRemark" : "",
  "filingTime" : "",
  "filingAcc" : "",
  "isNewFiling" : "",
  "adverseEvent" : "",
  "defined1" : "",
  "defined2" : "",
  "defined3" : "",
  "defined4" : "",
  "defined5" : "",
  "defined6" : "",
  "defined7" : "",
  "defined8" : "",
  "defined9" : "",
  "deliveryTime" : "",
  "remindFollowTime" : "",
  "inputTime" : "",
  "inputAcc" : "",
  "updateTime" : "",
  "updateAcc" : "",
  "isDel" : "",
  "remarkLabels" : [ ],
  "degrees" : [ ],
  "workYears" : [ ],
  "jobIds" : [ ],
  "trades" : [ ],
  "notes" : [ ],
  "jobTitle" : "HRBP",
  "dept" : "",
  "age" : "",
  "workYear" : "",
  "resumeNums" : "",
  "ownerName" : "",
  "interviewers" : [ ],
  "hrAcc" : "",
  "ids" : [ ],
  "words" : "",
  "deleteType" : "",
  "resumeChannelIds" : [ ],
  "currentAcc" : "",
  "isFollowRemind" : "",
  "deliveryTimes" : [ ],
  "jobType" : "",
  "interviewStatus" : "",
  "searchInClient" : ""
}, {
  "orderKey" : "",
  "keyType" : "",
  "keyWord" : "",
  "id" : "f38bc3a469b145d4a3601d8827b1b547",
  "orgId" : "",
  "resumeInfoId" : "",
  "resumeChannelId" : "514634870308",
  "channel" : 1,
  "photoUrl" : "",
  "name" : "刘丽莉",
  "sex" : "",
  "jobId" : "3df6f963f94246628a67e94deb989f72",
  "jobTitleEmail" : "",
  "jobArea" : "",
  "readStatus" : "",
  "downloadStatus" : "",
  "status" : 2,
  "statusChangeTime" : "",
  "resumeType" : 1,
  "interviewLevel" : "",
  "interviewTime" : "",
  "isFeedback" : "",
  "isChangeDate" : "",
  "interviewer" : "",
  "offerSendTime" : "",
  "offerStatus" : "",
  "expectedEntryTime" : "",
  "remarkLabel" : "",
  "degree" : "",
  "birthYear" : "",
  "startWorkingYear" : "",
  "maritalStatus" : "",
  "mobilephone" : "",
  "email" : "",
  "currentAddress" : "",
  "expectedAddress" : "",
  "expectedJobTitle" : "",
  "trade" : "",
  "workStatus" : "",
  "company" : "",
  "lastJobTitle" : "",
  "lastJobStart" : "",
  "lastJobEnd" : "",
  "lastSchool" : "",
  "lastMajor" : "",
  "lastSchoolStart" : "",
  "lastSchoolEnd" : "",
  "originalEmail" : "",
  "originalWay" : "",
  "isLock" : "",
  "libType" : 1,
  "havaSame" : "",
  "filingReason" : "",
  "filingRemark" : "",
  "filingTime" : "",
  "filingAcc" : "",
  "isNewFiling" : "",
  "adverseEvent" : "",
  "defined1" : "",
  "defined2" : "",
  "defined3" : "",
  "defined4" : "",
  "defined5" : "",
  "defined6" : "",
  "defined7" : "",
  "defined8" : "",
  "defined9" : "",
  "deliveryTime" : "",
  "remindFollowTime" : "",
  "inputTime" : "",
  "inputAcc" : "",
  "updateTime" : "",
  "updateAcc" : "",
  "isDel" : "",
  "remarkLabels" : [ ],
  "degrees" : [ ],
  "workYears" : [ ],
  "jobIds" : [ ],
  "trades" : [ ],
  "notes" : [ ],
  "jobTitle" : "HRBP",
  "dept" : "",
  "age" : "",
  "workYear" : "",
  "resumeNums" : "",
  "ownerName" : "",
  "interviewers" : [ ],
  "hrAcc" : "",
  "ids" : [ ],
  "words" : "",
  "deleteType" : "",
  "resumeChannelIds" : [ ],
  "currentAcc" : "",
  "isFollowRemind" : "",
  "deliveryTimes" : [ ],
  "jobType" : "",
  "interviewStatus" : "",
  "searchInClient" : ""
}, {
  "orderKey" : "",
  "keyType" : "",
  "keyWord" : "",
  "id" : "3fb73a89657e4dbda40b9938da38934a",
  "orgId" : "",
  "resumeInfoId" : "",
  "resumeChannelId" : "514623009608",
  "channel" : 1,
  "photoUrl" : "",
  "name" : "李丹晖",
  "sex" : "",
  "jobId" : "4bc241771db148429e8aa42541be081b",
  "jobTitleEmail" : "",
  "jobArea" : "",
  "readStatus" : "",
  "downloadStatus" : "",
  "status" : 0,
  "statusChangeTime" : "",
  "resumeType" : 1,
  "interviewLevel" : "",
  "interviewTime" : "",
  "isFeedback" : "",
  "isChangeDate" : "",
  "interviewer" : "",
  "offerSendTime" : "",
  "offerStatus" : "",
  "expectedEntryTime" : "",
  "remarkLabel" : "",
  "degree" : "",
  "birthYear" : "",
  "startWorkingYear" : "",
  "maritalStatus" : "",
  "mobilephone" : "",
  "email" : "",
  "currentAddress" : "",
  "expectedAddress" : "",
  "expectedJobTitle" : "",
  "trade" : "",
  "workStatus" : "",
  "company" : "",
  "lastJobTitle" : "",
  "lastJobStart" : "",
  "lastJobEnd" : "",
  "lastSchool" : "",
  "lastMajor" : "",
  "lastSchoolStart" : "",
  "lastSchoolEnd" : "",
  "originalEmail" : "",
  "originalWay" : "",
  "isLock" : "",
  "libType" : 1,
  "havaSame" : "",
  "filingReason" : "",
  "filingRemark" : "",
  "filingTime" : "",
  "filingAcc" : "",
  "isNewFiling" : "",
  "adverseEvent" : "",
  "defined1" : "",
  "defined2" : "",
  "defined3" : "",
  "defined4" : "",
  "defined5" : "",
  "defined6" : "",
  "defined7" : "",
  "defined8" : "",
  "defined9" : "",
  "deliveryTime" : "",
  "remindFollowTime" : "",
  "inputTime" : "",
  "inputAcc" : "",
  "updateTime" : "",
  "updateAcc" : "",
  "isDel" : "",
  "remarkLabels" : [ ],
  "degrees" : [ ],
  "workYears" : [ ],
  "jobIds" : [ ],
  "trades" : [ ],
  "notes" : [ ],
  "jobTitle" : "HRBP",
  "dept" : "",
  "age" : "",
  "workYear" : "",
  "resumeNums" : "",
  "ownerName" : "",
  "interviewers" : [ ],
  "hrAcc" : "",
  "ids" : [ ],
  "words" : "",
  "deleteType" : "",
  "resumeChannelIds" : [ ],
  "currentAcc" : "",
  "isFollowRemind" : "",
  "deliveryTimes" : [ ],
  "jobType" : "",
  "interviewStatus" : "",
  "searchInClient" : ""
}, {
  "orderKey" : "",
  "keyType" : "",
  "keyWord" : "",
  "id" : "5f3579d2ea514bc0a62bc94a35856239",
  "orgId" : "",
  "resumeInfoId" : "",
  "resumeChannelId" : "514623009608",
  "channel" : 1,
  "photoUrl" : "",
  "name" : "李丹晖",
  "sex" : "",
  "jobId" : "3df6f963f94246628a67e94deb989f72",
  "jobTitleEmail" : "",
  "jobArea" : "",
  "readStatus" : "",
  "downloadStatus" : "",
  "status" : 0,
  "statusChangeTime" : "",
  "resumeType" : 1,
  "interviewLevel" : "",
  "interviewTime" : "",
  "isFeedback" : "",
  "isChangeDate" : "",
  "interviewer" : "",
  "offerSendTime" : "",
  "offerStatus" : "",
  "expectedEntryTime" : "",
  "remarkLabel" : "",
  "degree" : "",
  "birthYear" : "",
  "startWorkingYear" : "",
  "maritalStatus" : "",
  "mobilephone" : "",
  "email" : "",
  "currentAddress" : "",
  "expectedAddress" : "",
  "expectedJobTitle" : "",
  "trade" : "",
  "workStatus" : "",
  "company" : "",
  "lastJobTitle" : "",
  "lastJobStart" : "",
  "lastJobEnd" : "",
  "lastSchool" : "",
  "lastMajor" : "",
  "lastSchoolStart" : "",
  "lastSchoolEnd" : "",
  "originalEmail" : "",
  "originalWay" : "",
  "isLock" : "",
  "libType" : 1,
  "havaSame" : "",
  "filingReason" : "",
  "filingRemark" : "",
  "filingTime" : "",
  "filingAcc" : "",
  "isNewFiling" : "",
  "adverseEvent" : "",
  "defined1" : "",
  "defined2" : "",
  "defined3" : "",
  "defined4" : "",
  "defined5" : "",
  "defined6" : "",
  "defined7" : "",
  "defined8" : "",
  "defined9" : "",
  "deliveryTime" : "",
  "remindFollowTime" : "",
  "inputTime" : "",
  "inputAcc" : "",
  "updateTime" : "",
  "updateAcc" : "",
  "isDel" : "",
  "remarkLabels" : [ ],
  "degrees" : [ ],
  "workYears" : [ ],
  "jobIds" : [ ],
  "trades" : [ ],
  "notes" : [ ],
  "jobTitle" : "HRBP",
  "dept" : "",
  "age" : "",
  "workYear" : "",
  "resumeNums" : "",
  "ownerName" : "",
  "interviewers" : [ ],
  "hrAcc" : "",
  "ids" : [ ],
  "words" : "",
  "deleteType" : "",
  "resumeChannelIds" : [ ],
  "currentAcc" : "",
  "isFollowRemind" : "",
  "deliveryTimes" : [ ],
  "jobType" : "",
  "interviewStatus" : "",
  "searchInClient" : ""
}, {
  "orderKey" : "",
  "keyType" : "",
  "keyWord" : "",
  "id" : "6b288e616dc44082a2139dafaf2ccd82",
  "orgId" : "",
  "resumeInfoId" : "",
  "resumeChannelId" : "514623009608",
  "channel" : 1,
  "photoUrl" : "",
  "name" : "李丹晖",
  "sex" : "",
  "jobId" : "3df6f963f94246628a67e94deb989f72",
  "jobTitleEmail" : "",
  "jobArea" : "",
  "readStatus" : "",
  "downloadStatus" : "",
  "status" : 0,
  "statusChangeTime" : "",
  "resumeType" : 1,
  "interviewLevel" : "",
  "interviewTime" : "",
  "isFeedback" : "",
  "isChangeDate" : "",
  "interviewer" : "",
  "offerSendTime" : "",
  "offerStatus" : "",
  "expectedEntryTime" : "",
  "remarkLabel" : "",
  "degree" : "",
  "birthYear" : "",
  "startWorkingYear" : "",
  "maritalStatus" : "",
  "mobilephone" : "",
  "email" : "",
  "currentAddress" : "",
  "expectedAddress" : "",
  "expectedJobTitle" : "",
  "trade" : "",
  "workStatus" : "",
  "company" : "",
  "lastJobTitle" : "",
  "lastJobStart" : "",
  "lastJobEnd" : "",
  "lastSchool" : "",
  "lastMajor" : "",
  "lastSchoolStart" : "",
  "lastSchoolEnd" : "",
  "originalEmail" : "",
  "originalWay" : "",
  "isLock" : "",
  "libType" : 3,
  "havaSame" : "",
  "filingReason" : "",
  "filingRemark" : "",
  "filingTime" : "",
  "filingAcc" : "",
  "isNewFiling" : "",
  "adverseEvent" : "",
  "defined1" : "",
  "defined2" : "",
  "defined3" : "",
  "defined4" : "",
  "defined5" : "",
  "defined6" : "",
  "defined7" : "",
  "defined8" : "",
  "defined9" : "",
  "deliveryTime" : "",
  "remindFollowTime" : "",
  "inputTime" : "",
  "inputAcc" : "",
  "updateTime" : "",
  "updateAcc" : "",
  "isDel" : "",
  "remarkLabels" : [ ],
  "degrees" : [ ],
  "workYears" : [ ],
  "jobIds" : [ ],
  "trades" : [ ],
  "notes" : [ ],
  "jobTitle" : "HRBP",
  "dept" : "",
  "age" : "",
  "workYear" : "",
  "resumeNums" : "",
  "ownerName" : "",
  "interviewers" : [ ],
  "hrAcc" : "",
  "ids" : [ ],
  "words" : "",
  "deleteType" : "",
  "resumeChannelIds" : [ ],
  "currentAcc" : "",
  "isFollowRemind" : "",
  "deliveryTimes" : [ ],
  "jobType" : "",
  "interviewStatus" : "",
  "searchInClient" : ""
} ]

    return (
      <div className="sameDetail-box">

        <ResumeDetailView {...this.props}/>
      </div>
    )
  }
}
